# Site settings
name: Chi Yunng Lim
title: Chi Yunng Lim | MSc Data Science Student
description: MSc Data Science student with a passion for building intelligent solutions and transforming complex data into impactful decisions
url: https://belowwind-islander.github.io/
baseurl: ''
email: cyunng.lim@gmail.com
cover: https://belowwind-islander.github.io/img/og.png
logo: https://belowwind-islander.github.io/img/emojis/technologist.png
resume: https://belowwind-islander.github.io/resume.pdf
social:
  - title: email
    url: mailto:cyunng.lim@gmail.com
  - title: github
    url: https://github.com/belowwind-islander
  - title: linkedin
    url: https://www.linkedin.com/in/chi-yunng-lim-bb36811a6/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'
  - .obsidian/
  - .obsidian/**/*


keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
