title: Chi Yunng Lim
author:
  name: belowwind-islander
  email: cyunng.lim@gmail.com

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Use remote theme to get latest Minima version from GitHub
remote_theme: jekyll/minima
# theme: minima  # Comment out or remove this line

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

# Minima configuration
minima:
  # Available skins: classic, dark, auto, solarized, solarized-light, solarized-dark
  skin: solarized-dark  # Change this to switch themes
  
  # date_format: "%d %b %Y"
  
  # Uncomment and customize social links as needed
  social_links:
    - { platform: github, user_url: "https://github.com/belowwind-islander" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/chi-yunng-lim-bb36811a6" }
